apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ocis
    app.kubernetes.io/version: 7.1.4
    helm.sh/chart: ocis-0.7.0
  name: web
  namespace: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: d8cae2071ea381168a7cbe21363fa63c78399a6726cf52d877f4fef9788f5403
      labels:
        app: web
        app.kubernetes.io/instance: ocis
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ocis
        app.kubernetes.io/version: 7.1.4
        helm.sh/chart: ocis-0.7.0
    spec:
      containers:
        - args:
            - web
            - server
          command:
            - ocis
          env:
            - name: MICRO_REGISTRY
              value: nats-js-kv
            - name: MICRO_REGISTRY_ADDRESS
              value: nats:9233
            - name: OCIS_CORS_ALLOW_ORIGINS
              value: https://owncloud.dev.misumi-sumi.com
            - name: WEB_LOG_COLOR
              value: "false"
            - name: WEB_LOG_LEVEL
              value: info
            - name: WEB_LOG_PRETTY
              value: "false"
            - name: WEB_TRACING_ENABLED
              value: "false"
            - name: WEB_TRACING_TYPE
              value: jaeger
            - name: WEB_TRACING_ENDPOINT
            - name: WEB_TRACING_COLLECTOR
            - name: WEB_DEBUG_PPROF
              value: "false"
            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100
            - name: WEB_DEBUG_ADDR
              value: 0.0.0.0:9104
            - name: WEB_OIDC_AUTHORITY
              value: https://owncloud.dev.misumi-sumi.com
            - name: WEB_OIDC_CLIENT_ID
              value: web
            - name: WEB_OIDC_SCOPE
              value: openid profile email
            - name: WEB_UI_THEME_SERVER
              value: https://owncloud.dev.misumi-sumi.com
            - name: WEB_UI_THEME_PATH
              value: /themes/owncloud/theme.json
            - name: WEB_UI_CONFIG_SERVER
              value: https://owncloud.dev.misumi-sumi.com
            - name: WEB_OPTION_CONTEXTHELPERS_READ_MORE
              value: "true"
            - name: WEB_OPTION_DISABLE_FEEDBACK_LINK
              value: "true"
            - name: WEB_OPTION_TOKEN_STORAGE_LOCAL
              value: "true"
            - name: WEB_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: jwt-secret
          image: owncloud/ocis:7.1.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: metrics-debug
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          name: web
          ports:
            - containerPort: 9100
              name: http
            - containerPort: 9104
              name: metrics-debug
          resources: {}
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/ocis
              name: configs
            - mountPath: /var/lib/ocis/web/assets/apps
              name: apps
            - mountPath: /var/lib/ocis
              name: web-data
      nodeSelector:
        role.worker: piraeus
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - configMap:
            name: web-config
          name: configs
        - emptyDir: {}
          name: apps
        - name: web-data
          persistentVolumeClaim:
            claimName: web-data
