apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ocis
    app.kubernetes.io/version: 7.1.4
    helm.sh/chart: ocis-0.7.0
  name: postprocessing
  namespace: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postprocessing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postprocessing
        app.kubernetes.io/instance: ocis
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ocis
        app.kubernetes.io/version: 7.1.4
        helm.sh/chart: ocis-0.7.0
    spec:
      containers:
        - args:
            - postprocessing
            - server
          command:
            - ocis
          env:
            - name: MICRO_REGISTRY
              value: nats-js-kv
            - name: MICRO_REGISTRY_ADDRESS
              value: nats:9233
            - name: OCIS_EVENTS_ENDPOINT
              value: nats:9233
            - name: OCIS_PERSISTENT_STORE
              value: nats-js-kv
            - name: OCIS_PERSISTENT_STORE_NODES
              value: nats:9233
            - name: POSTPROCESSING_LOG_COLOR
              value: "false"
            - name: POSTPROCESSING_LOG_LEVEL
              value: info
            - name: POSTPROCESSING_LOG_PRETTY
              value: "false"
            - name: POSTPROCESSING_DEBUG_PPROF
              value: "false"
            - name: POSTPROCESSING_DEBUG_ADDR
              value: 0.0.0.0:9255
            - name: POSTPROCESSING_WORKERS
              value: "3"
          image: owncloud/ocis:7.1.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: metrics-debug
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          name: postprocessing
          ports:
            - containerPort: 9255
              name: metrics-debug
          resources: {}
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/ocis/messaging-system-ca
              name: messaging-system-ca
              readOnly: true
      nodeSelector:
        role.worker: piraeus
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - emptyDir: {}
          name: messaging-system-ca
