apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owncloud-admin-user
  namespace: owncloud
spec:
  data:
    - remoteRef:
        key: owncloud
        property: admin_user_id
      secretKey: user-id
    - remoteRef:
        key: owncloud
        property: admin_password
      secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: admin-user
