apiVersion: v1
data:
  graph-ldap-bind-password: WFJxejZ1Zk1IcXpPbVlPcnp2OTYyWVdvamkwc056
  idp-ldap-bind-password: bWZDWm1OWkhYZ29DMFNtNlh5VGJHT0hLTWl0NFJn
  reva-ldap-bind-password: RVlTRTJqZUtQZ2xTTXhxelNSd3JQRnRVWXE3eUxo
kind: Secret
metadata:
  name: ldap-bind-secrets
  namespace: owncloud
