apiVersion: v1
data:
  api-key: N2pUTTdVM1loeVVMbmt5dFZFNUx2b3JxckNJNnht
  user-id: NGEyMTMxODQtOGMxNS00NjMzLWFmYjMtM2ZmNmYzMjU0NTlh
kind: Secret
metadata:
  name: storage-system
  namespace: owncloud
