apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ocis
    app.kubernetes.io/version: 7.1.4
    helm.sh/chart: ocis-0.7.0
    ocis-metrics: enabled
  name: web
  namespace: owncloud
spec:
  ports:
    - appProtocol: http
      name: http
      port: 9100
      protocol: TCP
    - appProtocol: http
      name: metrics-debug
      port: 9104
      protocol: TCP
  selector:
    app: web
