apiVersion: v1
kind: Service
metadata:
  labels:
    app: storagesystem
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ocis
    app.kubernetes.io/version: 7.1.4
    helm.sh/chart: ocis-0.7.0
    ocis-metrics: enabled
  name: storagesystem
  namespace: owncloud
spec:
  ports:
    - appProtocol: grpc
      name: grpc
      port: 9215
      protocol: TCP
    - appProtocol: http
      name: http
      port: 9216
      protocol: TCP
    - appProtocol: http
      name: metrics-debug
      port: 9217
      protocol: TCP
  selector:
    app: storagesystem
