[argocd]
src.github = 'argoproj/argo-cd'
fetch.github = 'argoproj/argo-cd'

[cilium]
src.github = 'cilium/cilium'
fetch.github = 'cilium/cilium'

[gateway-api]
src.github = 'kubernetes-sigs/gateway-api'
fetch.github = 'kubernetes-sigs/gateway-api'

[piraeus-operator]
src.github = 'piraeusdatastore/piraeus-operator'
fetch.github = 'piraeusdatastore/piraeus-operator'

[ceph-csi-operator]
src.github = 'ceph/ceph-csi-operator'
fetch.github = 'ceph/ceph-csi-operator'
