apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.10.8
    helm.sh/chart: piraeus-2.10.8
  name: piraeus-operator-controller-manager
  namespace: piraeus-datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: piraeus-operator
      app.kubernetes.io/instance: piraeus-operator
      app.kubernetes.io/name: piraeus-datastore
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: piraeus-operator
        app.kubernetes.io/instance: piraeus-operator
        app.kubernetes.io/name: piraeus-datastore
    spec:
      affinity: {}
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
            - --leader-elect=true
          command:
            - /manager
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IMAGE_CONFIG_MAP_NAME
              value: piraeus-operator-image-config
          image: quay.io/piraeusdatastore/piraeus-operator:v2.10.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      nodeSelector: {}
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
      serviceAccountName: piraeus-operator
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: drbd.linbit.com/lost-quorum
        - effect: NoSchedule
          key: drbd.linbit.com/force-io-error
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: piraeus-operator-tls
