apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: piraeus-worker2-storage
spec:
  nodeSelector:
    kubernetes.io/hostname: piraeus-worker2
  storagePools:
    - lvmThinPool:
        thinPool: thin
        volumeGroup: piraeus-vg
      name: hdd-pool
      source:
        hostDevices:
          - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_incus_piraeus_disk
