apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.10.8
    helm.sh/chart: piraeus-2.10.8
  name: piraeus-operator-leader-election
  namespace: piraeus-datastore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: piraeus-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: piraeus-operator
    namespace: piraeus-datastore
