apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: piraeus-operator
  namespace: piraeus-datastore
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus-datastore
