apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.11.0
    helm.sh/chart: piraeus-2.11.0
  name: piraeus-operator
  namespace: piraeus-datastore
