apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.11.0
    helm.sh/chart: piraeus-2.11.0
  name: piraeus-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUxuZkFkZVNoWVg1bEZnTFdlZDlLZHd3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOekE0TURBMU4xb1hEVE0yTURnd05EQTRNREExCk4xb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdKVm9UZHBlTnl6K1VmTmlnZjlNRkhmVlZON1cyU1lIem1KUmNTU255RThDaERxZFpIMFpBRGFRCi9QOHFPaTJ5MmE0QUEzYTRTTjJXUFZkS2ZrYTJwK0JjNWt1aXlZNWM0SXRtbFBBT1d4VmdBM2grcFFpcEo4bkwKL1J2bUIzbGVDdjRNQ2RiVUxLQ1BZUjBkanp2Y01YVWRiMnJFNzVjRU4xUHhNT08yaDJYYzBlUFd2amN6RUJSZgpyQUtmYU5sTFFrMHN5UndCYXZRTFU3NkplbXRoR283bGNFM3VMNHl1N0s3a3BERGhINld0dU01WWpwMXlNS0hqCldrdkpIZmkxbzk1TXoyajZzOXZFcEhtRzl1d2ZzSFJJUk95Mk9FWDYvenE1SGtwZFlJRmhsbkpHeFhjM05OYkkKTkVWdzFvNk92Ly9iN0k1T2JycXlnK1c1NkIzdFRRSURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhnb0dhMmJEMjF0OFpNMgpVWkZhSkJCS2RXQk9wbzlHbFlTdzdQbVJMTnJhMWpYQkdLZ3Z6SlRoWi9XdnJCZFhEUU1oWW5Qb0Fzb01JSTJiCmNkR1RNbG56ck5DdlNCYS9PRXE3WWJjT0ZodENKZVYvZDZXVncraWxRTkZ0ejlYT1d1Q2FBOWpLcHdVOEpoU04KdGpXbC9aUjhlbFNHZ2M5UG1Wd0RrWExYZEpFYTR0cmsvaUZZb21ZZ2dCQjJvWko4YVpDU1RWalpXSGxSNkFvawpZVGRqWjZCOFRrNWNGMk9zTmJ1Snpkd3M2dXpBbFhOTG0wVkVEbGdXSjhUd21ZZXczQjZoamlZdGpKSE13NndJCjFvdlRYU1dFL1Q0ZWF3UzRVcE1UT1llaDM1a1ZWR2Z5aUVEdHRLUHdZZmk1QzdYUHVLRDZhZnhpdStYeEZrdjQKbEFSYzhuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorcluster
    failurePolicy: Fail
    name: vlinstorcluster.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorclusters
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUxuZkFkZVNoWVg1bEZnTFdlZDlLZHd3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOekE0TURBMU4xb1hEVE0yTURnd05EQTRNREExCk4xb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdKVm9UZHBlTnl6K1VmTmlnZjlNRkhmVlZON1cyU1lIem1KUmNTU255RThDaERxZFpIMFpBRGFRCi9QOHFPaTJ5MmE0QUEzYTRTTjJXUFZkS2ZrYTJwK0JjNWt1aXlZNWM0SXRtbFBBT1d4VmdBM2grcFFpcEo4bkwKL1J2bUIzbGVDdjRNQ2RiVUxLQ1BZUjBkanp2Y01YVWRiMnJFNzVjRU4xUHhNT08yaDJYYzBlUFd2amN6RUJSZgpyQUtmYU5sTFFrMHN5UndCYXZRTFU3NkplbXRoR283bGNFM3VMNHl1N0s3a3BERGhINld0dU01WWpwMXlNS0hqCldrdkpIZmkxbzk1TXoyajZzOXZFcEhtRzl1d2ZzSFJJUk95Mk9FWDYvenE1SGtwZFlJRmhsbkpHeFhjM05OYkkKTkVWdzFvNk92Ly9iN0k1T2JycXlnK1c1NkIzdFRRSURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhnb0dhMmJEMjF0OFpNMgpVWkZhSkJCS2RXQk9wbzlHbFlTdzdQbVJMTnJhMWpYQkdLZ3Z6SlRoWi9XdnJCZFhEUU1oWW5Qb0Fzb01JSTJiCmNkR1RNbG56ck5DdlNCYS9PRXE3WWJjT0ZodENKZVYvZDZXVncraWxRTkZ0ejlYT1d1Q2FBOWpLcHdVOEpoU04KdGpXbC9aUjhlbFNHZ2M5UG1Wd0RrWExYZEpFYTR0cmsvaUZZb21ZZ2dCQjJvWko4YVpDU1RWalpXSGxSNkFvawpZVGRqWjZCOFRrNWNGMk9zTmJ1Snpkd3M2dXpBbFhOTG0wVkVEbGdXSjhUd21ZZXczQjZoamlZdGpKSE13NndJCjFvdlRYU1dFL1Q0ZWF3UzRVcE1UT1llaDM1a1ZWR2Z5aUVEdHRLUHdZZmk1QzdYUHVLRDZhZnhpdStYeEZrdjQKbEFSYzhuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstornodeconnection
    failurePolicy: Fail
    name: vlinstornodeconnection.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstornodeconnections
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUxuZkFkZVNoWVg1bEZnTFdlZDlLZHd3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOekE0TURBMU4xb1hEVE0yTURnd05EQTRNREExCk4xb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdKVm9UZHBlTnl6K1VmTmlnZjlNRkhmVlZON1cyU1lIem1KUmNTU255RThDaERxZFpIMFpBRGFRCi9QOHFPaTJ5MmE0QUEzYTRTTjJXUFZkS2ZrYTJwK0JjNWt1aXlZNWM0SXRtbFBBT1d4VmdBM2grcFFpcEo4bkwKL1J2bUIzbGVDdjRNQ2RiVUxLQ1BZUjBkanp2Y01YVWRiMnJFNzVjRU4xUHhNT08yaDJYYzBlUFd2amN6RUJSZgpyQUtmYU5sTFFrMHN5UndCYXZRTFU3NkplbXRoR283bGNFM3VMNHl1N0s3a3BERGhINld0dU01WWpwMXlNS0hqCldrdkpIZmkxbzk1TXoyajZzOXZFcEhtRzl1d2ZzSFJJUk95Mk9FWDYvenE1SGtwZFlJRmhsbkpHeFhjM05OYkkKTkVWdzFvNk92Ly9iN0k1T2JycXlnK1c1NkIzdFRRSURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhnb0dhMmJEMjF0OFpNMgpVWkZhSkJCS2RXQk9wbzlHbFlTdzdQbVJMTnJhMWpYQkdLZ3Z6SlRoWi9XdnJCZFhEUU1oWW5Qb0Fzb01JSTJiCmNkR1RNbG56ck5DdlNCYS9PRXE3WWJjT0ZodENKZVYvZDZXVncraWxRTkZ0ejlYT1d1Q2FBOWpLcHdVOEpoU04KdGpXbC9aUjhlbFNHZ2M5UG1Wd0RrWExYZEpFYTR0cmsvaUZZb21ZZ2dCQjJvWko4YVpDU1RWalpXSGxSNkFvawpZVGRqWjZCOFRrNWNGMk9zTmJ1Snpkd3M2dXpBbFhOTG0wVkVEbGdXSjhUd21ZZXczQjZoamlZdGpKSE13NndJCjFvdlRYU1dFL1Q0ZWF3UzRVcE1UT1llaDM1a1ZWR2Z5aUVEdHRLUHdZZmk1QzdYUHVLRDZhZnhpdStYeEZrdjQKbEFSYzhuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatellite
    failurePolicy: Fail
    name: vlinstorsatellite.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatellites
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUxuZkFkZVNoWVg1bEZnTFdlZDlLZHd3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOekE0TURBMU4xb1hEVE0yTURnd05EQTRNREExCk4xb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdKVm9UZHBlTnl6K1VmTmlnZjlNRkhmVlZON1cyU1lIem1KUmNTU255RThDaERxZFpIMFpBRGFRCi9QOHFPaTJ5MmE0QUEzYTRTTjJXUFZkS2ZrYTJwK0JjNWt1aXlZNWM0SXRtbFBBT1d4VmdBM2grcFFpcEo4bkwKL1J2bUIzbGVDdjRNQ2RiVUxLQ1BZUjBkanp2Y01YVWRiMnJFNzVjRU4xUHhNT08yaDJYYzBlUFd2amN6RUJSZgpyQUtmYU5sTFFrMHN5UndCYXZRTFU3NkplbXRoR283bGNFM3VMNHl1N0s3a3BERGhINld0dU01WWpwMXlNS0hqCldrdkpIZmkxbzk1TXoyajZzOXZFcEhtRzl1d2ZzSFJJUk95Mk9FWDYvenE1SGtwZFlJRmhsbkpHeFhjM05OYkkKTkVWdzFvNk92Ly9iN0k1T2JycXlnK1c1NkIzdFRRSURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhnb0dhMmJEMjF0OFpNMgpVWkZhSkJCS2RXQk9wbzlHbFlTdzdQbVJMTnJhMWpYQkdLZ3Z6SlRoWi9XdnJCZFhEUU1oWW5Qb0Fzb01JSTJiCmNkR1RNbG56ck5DdlNCYS9PRXE3WWJjT0ZodENKZVYvZDZXVncraWxRTkZ0ejlYT1d1Q2FBOWpLcHdVOEpoU04KdGpXbC9aUjhlbFNHZ2M5UG1Wd0RrWExYZEpFYTR0cmsvaUZZb21ZZ2dCQjJvWko4YVpDU1RWalpXSGxSNkFvawpZVGRqWjZCOFRrNWNGMk9zTmJ1Snpkd3M2dXpBbFhOTG0wVkVEbGdXSjhUd21ZZXczQjZoamlZdGpKSE13NndJCjFvdlRYU1dFL1Q0ZWF3UzRVcE1UT1llaDM1a1ZWR2Z5aUVEdHRLUHdZZmk1QzdYUHVLRDZhZnhpdStYeEZrdjQKbEFSYzhuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatelliteconfiguration
    failurePolicy: Fail
    name: vlinstorsatelliteconfiguration.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatelliteconfigurations
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUxuZkFkZVNoWVg1bEZnTFdlZDlLZHd3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOekE0TURBMU4xb1hEVE0yTURnd05EQTRNREExCk4xb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXdKVm9UZHBlTnl6K1VmTmlnZjlNRkhmVlZON1cyU1lIem1KUmNTU255RThDaERxZFpIMFpBRGFRCi9QOHFPaTJ5MmE0QUEzYTRTTjJXUFZkS2ZrYTJwK0JjNWt1aXlZNWM0SXRtbFBBT1d4VmdBM2grcFFpcEo4bkwKL1J2bUIzbGVDdjRNQ2RiVUxLQ1BZUjBkanp2Y01YVWRiMnJFNzVjRU4xUHhNT08yaDJYYzBlUFd2amN6RUJSZgpyQUtmYU5sTFFrMHN5UndCYXZRTFU3NkplbXRoR283bGNFM3VMNHl1N0s3a3BERGhINld0dU01WWpwMXlNS0hqCldrdkpIZmkxbzk1TXoyajZzOXZFcEhtRzl1d2ZzSFJJUk95Mk9FWDYvenE1SGtwZFlJRmhsbkpHeFhjM05OYkkKTkVWdzFvNk92Ly9iN0k1T2JycXlnK1c1NkIzdFRRSURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhnb0dhMmJEMjF0OFpNMgpVWkZhSkJCS2RXQk9wbzlHbFlTdzdQbVJMTnJhMWpYQkdLZ3Z6SlRoWi9XdnJCZFhEUU1oWW5Qb0Fzb01JSTJiCmNkR1RNbG56ck5DdlNCYS9PRXE3WWJjT0ZodENKZVYvZDZXVncraWxRTkZ0ejlYT1d1Q2FBOWpLcHdVOEpoU04KdGpXbC9aUjhlbFNHZ2M5UG1Wd0RrWExYZEpFYTR0cmsvaUZZb21ZZ2dCQjJvWko4YVpDU1RWalpXSGxSNkFvawpZVGRqWjZCOFRrNWNGMk9zTmJ1Snpkd3M2dXpBbFhOTG0wVkVEbGdXSjhUd21ZZXczQjZoamlZdGpKSE13NndJCjFvdlRYU1dFL1Q0ZWF3UzRVcE1UT1llaDM1a1ZWR2Z5aUVEdHRLUHdZZmk1QzdYUHVLRDZhZnhpdStYeEZrdjQKbEFSYzhuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-storage-k8s-io-v1-storageclass
    failurePolicy: Fail
    name: vstorageclass.kb.io
    rules:
      - apiGroups:
          - storage.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - storageclasses
    sideEffects: None
    timeoutSeconds: 2
