apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.10.8
    helm.sh/chart: piraeus-2.10.8
  name: piraeus-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lRVnFFTlVwN3FoSmwrNnJFMmdvdWFQVEFOQmdrcWhraUc5dzBCQVFzRkFEQkIKTVQ4d1BRWURWUVFERXpad2FYSmhaWFZ6TFc5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzJWeWRtbGpaUzV3YVhKaApaWFZ6TFdSaGRHRnpkRzl5WlM1emRtTXdIaGNOTWpZd09EQTBNVEUwTlRRM1doY05Nell3T0RBeE1URTBOVFEzCldqQkJNVDh3UFFZRFZRUURFelp3YVhKaFpYVnpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXcKYVhKaFpYVnpMV1JoZEdGemRHOXlaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEQmNza2ZCdFZJUWRnVUg2SFVhTld2dkJkWHlKYWxyUzVHMDBxcDY5SUlhekNZcVUxVmFCTkhOS1VuCmM4MmoxRVM2eFVsNFFrSUkvU2FlTWR0TlVOUlE5QkJQQzB5ZFVtT24vMFhOWVNiUnNDOVArbXc1c3I5S3h0WHIKRStsL3FKUW5la2ZsbWpvY2g3cFN5MzF4RVcyZVoveVRvbXphU3ppWlltTUJqNTdqNkFySkdTR1VNTTZBdTlhcgpPVjRmbjRFd0pLYUU0eUZadC9JbFF4R0RSdGFoNERieUFWdlp3b21LSGJlWVNubXViUWJodkVsdzg2NFNiNzYvCnBvRGpMUGM2UmVKY1ZVcGplcy9XNmdoNUdOZTgxOExFcUlnVTlpQk45SGs5Tk9GVy9KMGE2MWdSWGFXL3lWVS8KMVFaSlJZTWtHUzJYbGtHekFpaHdiNXRvRUNkeEFnTUJBQUdqZ1lNd2dZQXdEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNRUVHCkExVWRFUVE2TURpQ05uQnBjbUZsZFhNdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5CcGNtRmwKZFhNdFpHRjBZWE4wYjNKbExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWJkVTR5c2pLYzE5SnlyTwovUjhSSHQzbC9vNWxJYkhKcCtGVWRHSGttR3BrdnFmZTZGRjRRbjFoR0RFWGw2K1RlVEdoNG1nWXkwNlpKNDRjCjNjVy9IQ3lONlNrdSsyNmZKRDd4NDh3TnhrU3NuS051bFl3VHRKVzhQWEVjSUQ2NkdkM0NRNHFtMCtOZ0tyVmoKK0lwR3VTS1V2YlpvbkxydWtMbFR2c2JtcitrZU52dmM5ZlFEOTZqci9NbHQrVEtVSkNGY1laaGwwQXNBL25tUAo1MHluTWVwMVQwcXFhSk5IY2g4OW1wMHJYOUFIU1dXeXdaUEMyRE1aZHZEdGVkQUVQSm8zaUIrZTZ6Z1BPQkNqClpSUkFVY2hoLzl6VVNhK1NocW9PWFVkVFpOS3NrTDYxbDM0dTNMaWFkR0lBeU5LWEorVE1zUjFZWnlIUDJjL1kKQUY2d2xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorcluster
    failurePolicy: Fail
    name: vlinstorcluster.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorclusters
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lRVnFFTlVwN3FoSmwrNnJFMmdvdWFQVEFOQmdrcWhraUc5dzBCQVFzRkFEQkIKTVQ4d1BRWURWUVFERXpad2FYSmhaWFZ6TFc5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzJWeWRtbGpaUzV3YVhKaApaWFZ6TFdSaGRHRnpkRzl5WlM1emRtTXdIaGNOTWpZd09EQTBNVEUwTlRRM1doY05Nell3T0RBeE1URTBOVFEzCldqQkJNVDh3UFFZRFZRUURFelp3YVhKaFpYVnpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXcKYVhKaFpYVnpMV1JoZEdGemRHOXlaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEQmNza2ZCdFZJUWRnVUg2SFVhTld2dkJkWHlKYWxyUzVHMDBxcDY5SUlhekNZcVUxVmFCTkhOS1VuCmM4MmoxRVM2eFVsNFFrSUkvU2FlTWR0TlVOUlE5QkJQQzB5ZFVtT24vMFhOWVNiUnNDOVArbXc1c3I5S3h0WHIKRStsL3FKUW5la2ZsbWpvY2g3cFN5MzF4RVcyZVoveVRvbXphU3ppWlltTUJqNTdqNkFySkdTR1VNTTZBdTlhcgpPVjRmbjRFd0pLYUU0eUZadC9JbFF4R0RSdGFoNERieUFWdlp3b21LSGJlWVNubXViUWJodkVsdzg2NFNiNzYvCnBvRGpMUGM2UmVKY1ZVcGplcy9XNmdoNUdOZTgxOExFcUlnVTlpQk45SGs5Tk9GVy9KMGE2MWdSWGFXL3lWVS8KMVFaSlJZTWtHUzJYbGtHekFpaHdiNXRvRUNkeEFnTUJBQUdqZ1lNd2dZQXdEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNRUVHCkExVWRFUVE2TURpQ05uQnBjbUZsZFhNdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5CcGNtRmwKZFhNdFpHRjBZWE4wYjNKbExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWJkVTR5c2pLYzE5SnlyTwovUjhSSHQzbC9vNWxJYkhKcCtGVWRHSGttR3BrdnFmZTZGRjRRbjFoR0RFWGw2K1RlVEdoNG1nWXkwNlpKNDRjCjNjVy9IQ3lONlNrdSsyNmZKRDd4NDh3TnhrU3NuS051bFl3VHRKVzhQWEVjSUQ2NkdkM0NRNHFtMCtOZ0tyVmoKK0lwR3VTS1V2YlpvbkxydWtMbFR2c2JtcitrZU52dmM5ZlFEOTZqci9NbHQrVEtVSkNGY1laaGwwQXNBL25tUAo1MHluTWVwMVQwcXFhSk5IY2g4OW1wMHJYOUFIU1dXeXdaUEMyRE1aZHZEdGVkQUVQSm8zaUIrZTZ6Z1BPQkNqClpSUkFVY2hoLzl6VVNhK1NocW9PWFVkVFpOS3NrTDYxbDM0dTNMaWFkR0lBeU5LWEorVE1zUjFZWnlIUDJjL1kKQUY2d2xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstornodeconnection
    failurePolicy: Fail
    name: vlinstornodeconnection.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstornodeconnections
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lRVnFFTlVwN3FoSmwrNnJFMmdvdWFQVEFOQmdrcWhraUc5dzBCQVFzRkFEQkIKTVQ4d1BRWURWUVFERXpad2FYSmhaWFZ6TFc5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzJWeWRtbGpaUzV3YVhKaApaWFZ6TFdSaGRHRnpkRzl5WlM1emRtTXdIaGNOTWpZd09EQTBNVEUwTlRRM1doY05Nell3T0RBeE1URTBOVFEzCldqQkJNVDh3UFFZRFZRUURFelp3YVhKaFpYVnpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXcKYVhKaFpYVnpMV1JoZEdGemRHOXlaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEQmNza2ZCdFZJUWRnVUg2SFVhTld2dkJkWHlKYWxyUzVHMDBxcDY5SUlhekNZcVUxVmFCTkhOS1VuCmM4MmoxRVM2eFVsNFFrSUkvU2FlTWR0TlVOUlE5QkJQQzB5ZFVtT24vMFhOWVNiUnNDOVArbXc1c3I5S3h0WHIKRStsL3FKUW5la2ZsbWpvY2g3cFN5MzF4RVcyZVoveVRvbXphU3ppWlltTUJqNTdqNkFySkdTR1VNTTZBdTlhcgpPVjRmbjRFd0pLYUU0eUZadC9JbFF4R0RSdGFoNERieUFWdlp3b21LSGJlWVNubXViUWJodkVsdzg2NFNiNzYvCnBvRGpMUGM2UmVKY1ZVcGplcy9XNmdoNUdOZTgxOExFcUlnVTlpQk45SGs5Tk9GVy9KMGE2MWdSWGFXL3lWVS8KMVFaSlJZTWtHUzJYbGtHekFpaHdiNXRvRUNkeEFnTUJBQUdqZ1lNd2dZQXdEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNRUVHCkExVWRFUVE2TURpQ05uQnBjbUZsZFhNdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5CcGNtRmwKZFhNdFpHRjBZWE4wYjNKbExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWJkVTR5c2pLYzE5SnlyTwovUjhSSHQzbC9vNWxJYkhKcCtGVWRHSGttR3BrdnFmZTZGRjRRbjFoR0RFWGw2K1RlVEdoNG1nWXkwNlpKNDRjCjNjVy9IQ3lONlNrdSsyNmZKRDd4NDh3TnhrU3NuS051bFl3VHRKVzhQWEVjSUQ2NkdkM0NRNHFtMCtOZ0tyVmoKK0lwR3VTS1V2YlpvbkxydWtMbFR2c2JtcitrZU52dmM5ZlFEOTZqci9NbHQrVEtVSkNGY1laaGwwQXNBL25tUAo1MHluTWVwMVQwcXFhSk5IY2g4OW1wMHJYOUFIU1dXeXdaUEMyRE1aZHZEdGVkQUVQSm8zaUIrZTZ6Z1BPQkNqClpSUkFVY2hoLzl6VVNhK1NocW9PWFVkVFpOS3NrTDYxbDM0dTNMaWFkR0lBeU5LWEorVE1zUjFZWnlIUDJjL1kKQUY2d2xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatellite
    failurePolicy: Fail
    name: vlinstorsatellite.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatellites
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lRVnFFTlVwN3FoSmwrNnJFMmdvdWFQVEFOQmdrcWhraUc5dzBCQVFzRkFEQkIKTVQ4d1BRWURWUVFERXpad2FYSmhaWFZ6TFc5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzJWeWRtbGpaUzV3YVhKaApaWFZ6TFdSaGRHRnpkRzl5WlM1emRtTXdIaGNOTWpZd09EQTBNVEUwTlRRM1doY05Nell3T0RBeE1URTBOVFEzCldqQkJNVDh3UFFZRFZRUURFelp3YVhKaFpYVnpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXcKYVhKaFpYVnpMV1JoZEdGemRHOXlaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEQmNza2ZCdFZJUWRnVUg2SFVhTld2dkJkWHlKYWxyUzVHMDBxcDY5SUlhekNZcVUxVmFCTkhOS1VuCmM4MmoxRVM2eFVsNFFrSUkvU2FlTWR0TlVOUlE5QkJQQzB5ZFVtT24vMFhOWVNiUnNDOVArbXc1c3I5S3h0WHIKRStsL3FKUW5la2ZsbWpvY2g3cFN5MzF4RVcyZVoveVRvbXphU3ppWlltTUJqNTdqNkFySkdTR1VNTTZBdTlhcgpPVjRmbjRFd0pLYUU0eUZadC9JbFF4R0RSdGFoNERieUFWdlp3b21LSGJlWVNubXViUWJodkVsdzg2NFNiNzYvCnBvRGpMUGM2UmVKY1ZVcGplcy9XNmdoNUdOZTgxOExFcUlnVTlpQk45SGs5Tk9GVy9KMGE2MWdSWGFXL3lWVS8KMVFaSlJZTWtHUzJYbGtHekFpaHdiNXRvRUNkeEFnTUJBQUdqZ1lNd2dZQXdEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNRUVHCkExVWRFUVE2TURpQ05uQnBjbUZsZFhNdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5CcGNtRmwKZFhNdFpHRjBZWE4wYjNKbExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWJkVTR5c2pLYzE5SnlyTwovUjhSSHQzbC9vNWxJYkhKcCtGVWRHSGttR3BrdnFmZTZGRjRRbjFoR0RFWGw2K1RlVEdoNG1nWXkwNlpKNDRjCjNjVy9IQ3lONlNrdSsyNmZKRDd4NDh3TnhrU3NuS051bFl3VHRKVzhQWEVjSUQ2NkdkM0NRNHFtMCtOZ0tyVmoKK0lwR3VTS1V2YlpvbkxydWtMbFR2c2JtcitrZU52dmM5ZlFEOTZqci9NbHQrVEtVSkNGY1laaGwwQXNBL25tUAo1MHluTWVwMVQwcXFhSk5IY2g4OW1wMHJYOUFIU1dXeXdaUEMyRE1aZHZEdGVkQUVQSm8zaUIrZTZ6Z1BPQkNqClpSUkFVY2hoLzl6VVNhK1NocW9PWFVkVFpOS3NrTDYxbDM0dTNMaWFkR0lBeU5LWEorVE1zUjFZWnlIUDJjL1kKQUY2d2xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatelliteconfiguration
    failurePolicy: Fail
    name: vlinstorsatelliteconfiguration.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatelliteconfigurations
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lRVnFFTlVwN3FoSmwrNnJFMmdvdWFQVEFOQmdrcWhraUc5dzBCQVFzRkFEQkIKTVQ4d1BRWURWUVFERXpad2FYSmhaWFZ6TFc5d1pYSmhkRzl5TFhkbFltaHZiMnN0YzJWeWRtbGpaUzV3YVhKaApaWFZ6TFdSaGRHRnpkRzl5WlM1emRtTXdIaGNOTWpZd09EQTBNVEUwTlRRM1doY05Nell3T0RBeE1URTBOVFEzCldqQkJNVDh3UFFZRFZRUURFelp3YVhKaFpYVnpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXcKYVhKaFpYVnpMV1JoZEdGemRHOXlaUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEQmNza2ZCdFZJUWRnVUg2SFVhTld2dkJkWHlKYWxyUzVHMDBxcDY5SUlhekNZcVUxVmFCTkhOS1VuCmM4MmoxRVM2eFVsNFFrSUkvU2FlTWR0TlVOUlE5QkJQQzB5ZFVtT24vMFhOWVNiUnNDOVArbXc1c3I5S3h0WHIKRStsL3FKUW5la2ZsbWpvY2g3cFN5MzF4RVcyZVoveVRvbXphU3ppWlltTUJqNTdqNkFySkdTR1VNTTZBdTlhcgpPVjRmbjRFd0pLYUU0eUZadC9JbFF4R0RSdGFoNERieUFWdlp3b21LSGJlWVNubXViUWJodkVsdzg2NFNiNzYvCnBvRGpMUGM2UmVKY1ZVcGplcy9XNmdoNUdOZTgxOExFcUlnVTlpQk45SGs5Tk9GVy9KMGE2MWdSWGFXL3lWVS8KMVFaSlJZTWtHUzJYbGtHekFpaHdiNXRvRUNkeEFnTUJBQUdqZ1lNd2dZQXdEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNRUVHCkExVWRFUVE2TURpQ05uQnBjbUZsZFhNdGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG5CcGNtRmwKZFhNdFpHRjBZWE4wYjNKbExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWJkVTR5c2pLYzE5SnlyTwovUjhSSHQzbC9vNWxJYkhKcCtGVWRHSGttR3BrdnFmZTZGRjRRbjFoR0RFWGw2K1RlVEdoNG1nWXkwNlpKNDRjCjNjVy9IQ3lONlNrdSsyNmZKRDd4NDh3TnhrU3NuS051bFl3VHRKVzhQWEVjSUQ2NkdkM0NRNHFtMCtOZ0tyVmoKK0lwR3VTS1V2YlpvbkxydWtMbFR2c2JtcitrZU52dmM5ZlFEOTZqci9NbHQrVEtVSkNGY1laaGwwQXNBL25tUAo1MHluTWVwMVQwcXFhSk5IY2g4OW1wMHJYOUFIU1dXeXdaUEMyRE1aZHZEdGVkQUVQSm8zaUIrZTZ6Z1BPQkNqClpSUkFVY2hoLzl6VVNhK1NocW9PWFVkVFpOS3NrTDYxbDM0dTNMaWFkR0lBeU5LWEorVE1zUjFZWnlIUDJjL1kKQUY2d2xBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-storage-k8s-io-v1-storageclass
    failurePolicy: Fail
    name: vstorageclass.kb.io
    rules:
      - apiGroups:
          - storage.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - storageclasses
    sideEffects: None
    timeoutSeconds: 2
