apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
    app.kubernetes.io/instance: piraeus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/version: v2.10.8
    helm.sh/chart: piraeus-2.10.8
  name: piraeus-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUphSU9TeG8zaGZ2Z3BCa2l0ZUZTc2t3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOREE0TURneE9Wb1hEVE0yTURnd01UQTRNRGd4Ck9Wb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTB2S0FzSGp1R3BWTmlHMTV4dHR1VERlTHM3d0RaMWxSQngycjBBOGF0RkVDR1ZYMDU0VlFZa3l0Cm4wUGc2NDk5WlhSTGhNZlZOdnNMZmg0cEIwdy9UVzhiQVd5YUo5bnFHR3VqaEJrTmpwUEl5NXZGSVByeElzNTcKRUtOZkdoRzdLMW9ZNGNSZ0xsOVY3blFlZ0ZEQXQwRXVWS09OZWowK0MzUUxBajhjKzdiL0pzNHNHZGZTUGVjWApPVFJvcStETnkwa1BRS3NVMUhDaUZEQmZnazZXUDFQZkdzMGg3bDNNa04rSjlPOWNYOHZUYkFEa0VkdTBYMmgwCktVUkVFbkRnWWpZbDJYRFRoaklqUENYYnhqMnFiUXJEb2RSUDZDcEVibXI0Y3FvL3V6MGQ3SjVWYnU1M2VOSEIKZHlESkwxRUZORDhKMVJINmtkVjYyOHF5aFZRTUp3SURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtnaEJSenFqd3ZqNFY1MwoyelB2SHNvZzRiSzY2Z1hGWEFvbExiWTN6NG0vRDZkd3Z0Q3FCUmFReTZzcU1EM1BQRHlKWVNSakRCTWhldUtUCmJ2QWF1QitWNFhJRmF1cGZ4bi9uMnBOUkhhcnc3TXE0Q3dFcHNLclN5bEhOdmpvT2tQTEhIQ1RpK1JjNGdjb2MKRlB4TW9Cbm5jKzdKb1BoNWl0K1VndG5xYlVqWjdEYnBhS2hGZnhYeHlWS0lWcXpuUjhrOGhHcFN3ajR3TTFJRApMWDhmRnhTUmh5aVZXKzJrWGpUMXh0MlVPVW9wTnFER2dEMllLTkJ1aTFDTU40V3ZuR2lUZFc2NlZVRFhieWlZCkVoVFdoQjAyT0ZjNzdmclg4dFFNNjJIUmxmcFE0V3F6ellqT1ppOVBMRmxpUXpFOGRtb29mNG53OFplOGhtNzgKd3hYeXRYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorcluster
    failurePolicy: Fail
    name: vlinstorcluster.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorclusters
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUphSU9TeG8zaGZ2Z3BCa2l0ZUZTc2t3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOREE0TURneE9Wb1hEVE0yTURnd01UQTRNRGd4Ck9Wb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTB2S0FzSGp1R3BWTmlHMTV4dHR1VERlTHM3d0RaMWxSQngycjBBOGF0RkVDR1ZYMDU0VlFZa3l0Cm4wUGc2NDk5WlhSTGhNZlZOdnNMZmg0cEIwdy9UVzhiQVd5YUo5bnFHR3VqaEJrTmpwUEl5NXZGSVByeElzNTcKRUtOZkdoRzdLMW9ZNGNSZ0xsOVY3blFlZ0ZEQXQwRXVWS09OZWowK0MzUUxBajhjKzdiL0pzNHNHZGZTUGVjWApPVFJvcStETnkwa1BRS3NVMUhDaUZEQmZnazZXUDFQZkdzMGg3bDNNa04rSjlPOWNYOHZUYkFEa0VkdTBYMmgwCktVUkVFbkRnWWpZbDJYRFRoaklqUENYYnhqMnFiUXJEb2RSUDZDcEVibXI0Y3FvL3V6MGQ3SjVWYnU1M2VOSEIKZHlESkwxRUZORDhKMVJINmtkVjYyOHF5aFZRTUp3SURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtnaEJSenFqd3ZqNFY1MwoyelB2SHNvZzRiSzY2Z1hGWEFvbExiWTN6NG0vRDZkd3Z0Q3FCUmFReTZzcU1EM1BQRHlKWVNSakRCTWhldUtUCmJ2QWF1QitWNFhJRmF1cGZ4bi9uMnBOUkhhcnc3TXE0Q3dFcHNLclN5bEhOdmpvT2tQTEhIQ1RpK1JjNGdjb2MKRlB4TW9Cbm5jKzdKb1BoNWl0K1VndG5xYlVqWjdEYnBhS2hGZnhYeHlWS0lWcXpuUjhrOGhHcFN3ajR3TTFJRApMWDhmRnhTUmh5aVZXKzJrWGpUMXh0MlVPVW9wTnFER2dEMllLTkJ1aTFDTU40V3ZuR2lUZFc2NlZVRFhieWlZCkVoVFdoQjAyT0ZjNzdmclg4dFFNNjJIUmxmcFE0V3F6ellqT1ppOVBMRmxpUXpFOGRtb29mNG53OFplOGhtNzgKd3hYeXRYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstornodeconnection
    failurePolicy: Fail
    name: vlinstornodeconnection.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstornodeconnections
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUphSU9TeG8zaGZ2Z3BCa2l0ZUZTc2t3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOREE0TURneE9Wb1hEVE0yTURnd01UQTRNRGd4Ck9Wb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTB2S0FzSGp1R3BWTmlHMTV4dHR1VERlTHM3d0RaMWxSQngycjBBOGF0RkVDR1ZYMDU0VlFZa3l0Cm4wUGc2NDk5WlhSTGhNZlZOdnNMZmg0cEIwdy9UVzhiQVd5YUo5bnFHR3VqaEJrTmpwUEl5NXZGSVByeElzNTcKRUtOZkdoRzdLMW9ZNGNSZ0xsOVY3blFlZ0ZEQXQwRXVWS09OZWowK0MzUUxBajhjKzdiL0pzNHNHZGZTUGVjWApPVFJvcStETnkwa1BRS3NVMUhDaUZEQmZnazZXUDFQZkdzMGg3bDNNa04rSjlPOWNYOHZUYkFEa0VkdTBYMmgwCktVUkVFbkRnWWpZbDJYRFRoaklqUENYYnhqMnFiUXJEb2RSUDZDcEVibXI0Y3FvL3V6MGQ3SjVWYnU1M2VOSEIKZHlESkwxRUZORDhKMVJINmtkVjYyOHF5aFZRTUp3SURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtnaEJSenFqd3ZqNFY1MwoyelB2SHNvZzRiSzY2Z1hGWEFvbExiWTN6NG0vRDZkd3Z0Q3FCUmFReTZzcU1EM1BQRHlKWVNSakRCTWhldUtUCmJ2QWF1QitWNFhJRmF1cGZ4bi9uMnBOUkhhcnc3TXE0Q3dFcHNLclN5bEhOdmpvT2tQTEhIQ1RpK1JjNGdjb2MKRlB4TW9Cbm5jKzdKb1BoNWl0K1VndG5xYlVqWjdEYnBhS2hGZnhYeHlWS0lWcXpuUjhrOGhHcFN3ajR3TTFJRApMWDhmRnhTUmh5aVZXKzJrWGpUMXh0MlVPVW9wTnFER2dEMllLTkJ1aTFDTU40V3ZuR2lUZFc2NlZVRFhieWlZCkVoVFdoQjAyT0ZjNzdmclg4dFFNNjJIUmxmcFE0V3F6ellqT1ppOVBMRmxpUXpFOGRtb29mNG53OFplOGhtNzgKd3hYeXRYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatellite
    failurePolicy: Fail
    name: vlinstorsatellite.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatellites
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUphSU9TeG8zaGZ2Z3BCa2l0ZUZTc2t3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOREE0TURneE9Wb1hEVE0yTURnd01UQTRNRGd4Ck9Wb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTB2S0FzSGp1R3BWTmlHMTV4dHR1VERlTHM3d0RaMWxSQngycjBBOGF0RkVDR1ZYMDU0VlFZa3l0Cm4wUGc2NDk5WlhSTGhNZlZOdnNMZmg0cEIwdy9UVzhiQVd5YUo5bnFHR3VqaEJrTmpwUEl5NXZGSVByeElzNTcKRUtOZkdoRzdLMW9ZNGNSZ0xsOVY3blFlZ0ZEQXQwRXVWS09OZWowK0MzUUxBajhjKzdiL0pzNHNHZGZTUGVjWApPVFJvcStETnkwa1BRS3NVMUhDaUZEQmZnazZXUDFQZkdzMGg3bDNNa04rSjlPOWNYOHZUYkFEa0VkdTBYMmgwCktVUkVFbkRnWWpZbDJYRFRoaklqUENYYnhqMnFiUXJEb2RSUDZDcEVibXI0Y3FvL3V6MGQ3SjVWYnU1M2VOSEIKZHlESkwxRUZORDhKMVJINmtkVjYyOHF5aFZRTUp3SURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtnaEJSenFqd3ZqNFY1MwoyelB2SHNvZzRiSzY2Z1hGWEFvbExiWTN6NG0vRDZkd3Z0Q3FCUmFReTZzcU1EM1BQRHlKWVNSakRCTWhldUtUCmJ2QWF1QitWNFhJRmF1cGZ4bi9uMnBOUkhhcnc3TXE0Q3dFcHNLclN5bEhOdmpvT2tQTEhIQ1RpK1JjNGdjb2MKRlB4TW9Cbm5jKzdKb1BoNWl0K1VndG5xYlVqWjdEYnBhS2hGZnhYeHlWS0lWcXpuUjhrOGhHcFN3ajR3TTFJRApMWDhmRnhTUmh5aVZXKzJrWGpUMXh0MlVPVW9wTnFER2dEMllLTkJ1aTFDTU40V3ZuR2lUZFc2NlZVRFhieWlZCkVoVFdoQjAyT0ZjNzdmclg4dFFNNjJIUmxmcFE0V3F6ellqT1ppOVBMRmxpUXpFOGRtb29mNG53OFplOGhtNzgKd3hYeXRYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-piraeus-io-v1-linstorsatelliteconfiguration
    failurePolicy: Fail
    name: vlinstorsatelliteconfiguration.kb.io
    rules:
      - apiGroups:
          - piraeus.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - linstorsatelliteconfigurations
    sideEffects: None
    timeoutSeconds: 2
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrVENDQW5tZ0F3SUJBZ0lSQUphSU9TeG8zaGZ2Z3BCa2l0ZUZTc2t3RFFZSktvWklodmNOQVFFTEJRQXcKUVRFL01EMEdBMVVFQXhNMmNHbHlZV1YxY3kxdmNHVnlZWFJ2Y2kxM1pXSm9iMjlyTFhObGNuWnBZMlV1Y0dseQpZV1YxY3kxa1lYUmhjM1J2Y21VdWMzWmpNQjRYRFRJMk1EZ3dOREE0TURneE9Wb1hEVE0yTURnd01UQTRNRGd4Ck9Wb3dRVEUvTUQwR0ExVUVBeE0yY0dseVlXVjFjeTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXUKY0dseVlXVjFjeTFrWVhSaGMzUnZjbVV1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQTB2S0FzSGp1R3BWTmlHMTV4dHR1VERlTHM3d0RaMWxSQngycjBBOGF0RkVDR1ZYMDU0VlFZa3l0Cm4wUGc2NDk5WlhSTGhNZlZOdnNMZmg0cEIwdy9UVzhiQVd5YUo5bnFHR3VqaEJrTmpwUEl5NXZGSVByeElzNTcKRUtOZkdoRzdLMW9ZNGNSZ0xsOVY3blFlZ0ZEQXQwRXVWS09OZWowK0MzUUxBajhjKzdiL0pzNHNHZGZTUGVjWApPVFJvcStETnkwa1BRS3NVMUhDaUZEQmZnazZXUDFQZkdzMGg3bDNNa04rSjlPOWNYOHZUYkFEa0VkdTBYMmgwCktVUkVFbkRnWWpZbDJYRFRoaklqUENYYnhqMnFiUXJEb2RSUDZDcEVibXI0Y3FvL3V6MGQ3SjVWYnU1M2VOSEIKZHlESkwxRUZORDhKMVJINmtkVjYyOHF5aFZRTUp3SURBUUFCbzRHRE1JR0FNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREJCCkJnTlZIUkVFT2pBNGdqWndhWEpoWlhWekxXOXdaWEpoZEc5eUxYZGxZbWh2YjJzdGMyVnlkbWxqWlM1d2FYSmgKWlhWekxXUmhkR0Z6ZEc5eVpTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtnaEJSenFqd3ZqNFY1MwoyelB2SHNvZzRiSzY2Z1hGWEFvbExiWTN6NG0vRDZkd3Z0Q3FCUmFReTZzcU1EM1BQRHlKWVNSakRCTWhldUtUCmJ2QWF1QitWNFhJRmF1cGZ4bi9uMnBOUkhhcnc3TXE0Q3dFcHNLclN5bEhOdmpvT2tQTEhIQ1RpK1JjNGdjb2MKRlB4TW9Cbm5jKzdKb1BoNWl0K1VndG5xYlVqWjdEYnBhS2hGZnhYeHlWS0lWcXpuUjhrOGhHcFN3ajR3TTFJRApMWDhmRnhTUmh5aVZXKzJrWGpUMXh0MlVPVW9wTnFER2dEMllLTkJ1aTFDTU40V3ZuR2lUZFc2NlZVRFhieWlZCkVoVFdoQjAyT0ZjNzdmclg4dFFNNjJIUmxmcFE0V3F6ellqT1ppOVBMRmxpUXpFOGRtb29mNG53OFplOGhtNzgKd3hYeXRYWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: piraeus-operator-webhook-service
        namespace: piraeus-datastore
        path: /validate-storage-k8s-io-v1-storageclass
    failurePolicy: Fail
    name: vstorageclass.kb.io
    rules:
      - apiGroups:
          - storage.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - storageclasses
    sideEffects: None
    timeoutSeconds: 2
