apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuakNDQW9hZ0F3SUJBZ0lVV0xkclVaRWY1QWdOYTlhVjNub0Q0bmZTN2NVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RU9NQXdHQTFVRUJoTUZTbUZ3WVc0eERUQUxCZ05WQkFnVEJFRnphV0V4RGpBTUJnTlZCQWNUQlZSdgphM2x2TVNBd0hnWURWUVFLRXhkUWNtOXFaV04wSUZGMVpXVnVkR1YwSUZKdmIzUkRRVEVVTUJJR0ExVUVBeE1MCmF6aHpMWEp2YjNRdFkyRXdIaGNOTWpZd05USTNNVEF5TmpBd1doY05NekV3TlRJMk1UQXlOakF3V2pCbk1RNHcKREFZRFZRUUdFd1ZLWVhCaGJqRU5NQXNHQTFVRUNCTUVRWE5wWVRFT01Bd0dBMVVFQnhNRlZHOXJlVzh4SURBZQpCZ05WQkFvVEYxQnliMnBsWTNRZ1VYVmxaVzUwWlhRZ1VtOXZkRU5CTVJRd0VnWURWUVFERXd0ck9ITXRjbTl2CmRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOZHQ2c3NGcmNFa2hyWWYKZGYyRGl6eHI2by8vWWlQR05nYnV3NjF1TGlTbExEdlJ0TUczWFNqWGREZzJkSENyOUtVYytaaTNYNGZMZHhsTwpvaXNFaFY1SDEzR1U2amxkMDlReGQ5QXlzQjdNTnFTUzluTFdzQkl2Y2xGN1ZBaVNaRDNEek4vMHA2RU1rVmFOCjlEK0p5czBJbjRMUW03ZjNONVI3UGhZQXZobUhDYTdwbUxFL3ZwZGIxRnVqTWxCOEJDZm16cTA1TzdLQjdiNk8KbUxjTWk1MWxINGZNcmxHUlQrc3E2ZzZ4dTl3Z1l1dEtwZDNqWnEzOXZsRi83dU5mV3lKdFZpSkVtV2pCSEYvRApueTJuNnRqcWgvYnQ1bzl5RjBTS0N2WVBTL2ZacFBkSlJlVzhkMzA0cGpzNjM0Zm1pczN3RmRiMWJPZFZHZDNJCkxvZTFOMGNDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKSFFZRFZSME9CQllFRkxZS0t1NGdlRlFUOFpGdmh5UTBNeUVYMDNrV01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUJybGc0OVJxaTdpaWVibmdldGhLYk92UDYycFRRZzFXdEdXQUl6ejJSekdqbG9lK1ZkdlVMQVhFOHY5UndWClltd1NsMjZtU1ZuQVlTQUtYbUU4V3pyRzYzSkJFbE5lUXpFaUVjNVlTanJ4cUVZdWNNYVd0RlZ0cEZ4VUMwV3MKTjI1N2J5eC9LaTRwVS9xL0QxanZpZzZMZEtLc1dSQXEwZXRGL3RsQjAwOXBUSmR1RWlqVTl0aGRFTWlWNVFjQwpMRHlDRkowZnpZc0JSd3cyUzgwQXNVdzlNN2hybDZrWXN2d3p4MGUzQ2I4djVnYnBibGsybHVaYnpIbFFKNjVGCm1hQWxKMUR1cUFxOHhCSmpPZ3dpbWtGNW9XdmJXSXdFV3grOTdUK0xma0ZiUDE5bU1BNU50b2lyQUJmR2F3TXoKUTh0UU1SbW9lWWdZZDVGRjg1MFpYWC83Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      path: secret
      server: https://172.16.11.1:8200
      version: v2
