# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  argocd = {
    pname = "argocd";
    version = "v3.4.5";
    src = fetchFromGitHub {
      owner = "argoproj";
      repo = "argo-cd";
      rev = "v3.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-hM7ss948dr7KntUGwiFDhr1OrbI+LAJlDgUMnegm+es=";
    };
  };
  cilium = {
    pname = "cilium";
    version = "v1.19.6";
    src = fetchFromGitHub {
      owner = "cilium";
      repo = "cilium";
      rev = "v1.19.6";
      fetchSubmodules = false;
      sha256 = "sha256-dbI34NJ4yxPvKNLivQUfMEK1vAL8lOXfK8gtWiqX+L0=";
    };
  };
  gateway-api = {
    pname = "gateway-api";
    version = "v1.6.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "gateway-api";
      rev = "v1.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-Hq3vaCQRSRFjya76qRYw4/BcH00Wu5wE6UQACrjKJSk=";
    };
  };
  piraeus-operator = {
    pname = "piraeus-operator";
    version = "v2.10.8";
    src = fetchFromGitHub {
      owner = "piraeusdatastore";
      repo = "piraeus-operator";
      rev = "v2.10.8";
      fetchSubmodules = false;
      sha256 = "sha256-/PbyUOUAzlQQSAnuyWjyap2RagPb4P6qoE5FXGhb8nI=";
    };
  };
}
