# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  argocd = {
    pname = "argocd";
    version = "v3.5.0";
    src = fetchFromGitHub {
      owner = "argoproj";
      repo = "argo-cd";
      rev = "v3.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-Lhxdpz/Mjg0zZpktJD6yBCNoL5aPtemJoSCQvKkBqsw=";
    };
  };
  cilium = {
    pname = "cilium";
    version = "v1.20.0";
    src = fetchFromGitHub {
      owner = "cilium";
      repo = "cilium";
      rev = "v1.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-iL41chnyFQIH1i6xHUdtkpwzJxDutw3of+8fvEd4B64=";
    };
  };
  gateway-api = {
    pname = "gateway-api";
    version = "v1.6.1";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "gateway-api";
      rev = "v1.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-Hq3vaCQRSRFjya76qRYw4/BcH00Wu5wE6UQACrjKJSk=";
    };
  };
  piraeus-operator = {
    pname = "piraeus-operator";
    version = "v2.11.0";
    src = fetchFromGitHub {
      owner = "piraeusdatastore";
      repo = "piraeus-operator";
      rev = "v2.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-LMIv1qERTgIWfGveuBVikDMphFVD1aFM8iEU5IhNJOQ=";
    };
  };
}
