apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k8s-apps/manifests/develop/rook-ceph
    repoURL: https://github.com/misumisumi/nixos-k8s-config.git
    targetRevision: refactor/k8s
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
