apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/develop/rook-ceph
    repoURL: https://github.com/misumisumi/homelab-k8s-apps.git
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
