apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  data:
    - remoteRef:
        key: alertmanager
        property: discord_webhook_url
      secretKey: discordWebhookUrl
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: alertmanager-config
    template:
      data:
        alertmanager.yaml: |
          route:
            group_by: ['alertname']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 4h
            receiver: discord
          receivers:
            - name: discord
              discord_configs:
                - webhook_url: '{{ .discordWebhookUrl }}'
                  send_resolved: true
      engineVersion: v2
