apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  data:
    - remoteRef:
        key: grafana
        property: github_client_id
      secretKey: GF_AUTH_GITHUB_CLIENT_ID
    - remoteRef:
        key: grafana
        property: github_client_secret
      secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: grafana-oauth
