apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  data:
    - remoteRef:
        key: grafana
        property: admin_user
      secretKey: admin-user
    - remoteRef:
        key: grafana
        property: admin_password
      secretKey: admin-password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: grafana-admin
