apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-41.1.1
  name: traefik
  namespace: traefik
spec:
  endpoints:
    - path: /metrics
      targetPort: metrics
  jobLabel: traefik
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/name: traefik
