apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dex-client
  namespace: argocd
spec:
  data:
    - remoteRef:
        key: argocd
        property: github_client_id
      secretKey: dex.github.clientID
    - remoteRef:
        key: argocd
        property: github_client_secret
      secretKey: dex.github.clientSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Merge
    name: argocd-secret
