apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicated-pool
  namespace: rook-ceph
spec:
  enableRBDStats: true
  failureDomain: host
  replicated:
    requireSafeReplicaSize: true
    size: 3
