apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piraeus-master-passphrase
  namespace: piraeus-datastore
spec:
  data:
    - remoteRef:
        key: piraeus
        property: master_passphrase
      secretKey: MASTER_PASSPHRASE
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    name: linstor-passphrase
