apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: misumi-sumi-com-tls
  namespace: kube-system
spec:
  dnsNames:
    - '*.misumi-sumi.com'
    - '*.k8s.misumi-sumi.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: misumi-sumi-com-tls
